services:
  - type: web
    name: docuchat-ai
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn doc_qa_project.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: GEMINI_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
