# Generated by Django 6.0.7 on 2026-07-30 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_app', '0002_document_summary_alter_document_full_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='latency_ms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='provider_used',
            field=models.CharField(default='Qwen3/Gemini', max_length=50),
        ),
        migrations.AddField(
            model_name='document',
            name='is_ocr_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AnalyticsMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('tokens_used', models.IntegerField(default=0)),
                ('latency_ms', models.IntegerField(default=0)),
                ('status', models.CharField(default='success', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
